version: '3.7'

services:
  backend:
    build:
      dockerfile: dockerfile
    container_name: "backend-app-dev"
    volumes:
      - .:/usr/src/app/
    expose:
      - 8000
    ports:
      - "8080:8000"
    networks:
      - dev
    depends_on:
      - db
    env_file:
      - env.dev



  db:
    image: postgres:13.2-alpine
    container_name: "db-dev"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - dev
    environment:
      - POSTGRES_USER=django
      - POSTGRES_PASSWORD=django
      - POSTGRES_DB=django_dev

volumes:
  postgres_data:

networks:
  dev:
