# Generated by Django 4.1.5 on 2023-01-04 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booktracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookusers',
            name='completed_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
