# Generated by Django 4.1.5 on 2023-01-04 16:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('booktracker', '0002_alter_bookusers_completed_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'verbose_name': 'Автор', 'verbose_name_plural': 'Авторы'},
        ),
        migrations.AlterModelOptions(
            name='book',
            options={'verbose_name': 'Книга', 'verbose_name_plural': 'Книги'},
        ),
        migrations.AlterModelOptions(
            name='bookreview',
            options={'verbose_name': 'Рецензия', 'verbose_name_plural': 'Рецензии'},
        ),
        migrations.AlterModelOptions(
            name='bookusers',
            options={'verbose_name': 'Книг пользователя', 'verbose_name_plural': 'Книги пользователя'},
        ),
        migrations.AlterModelOptions(
            name='mood',
            options={'verbose_name': 'Настроение после чтения', 'verbose_name_plural': 'Настроения после чтений'},
        ),
        migrations.AlterModelOptions(
            name='objectivereadingbook',
            options={'verbose_name': 'Цель по книге', 'verbose_name_plural': 'Цели по книгам'},
        ),
        migrations.AlterModelOptions(
            name='objectiveyear',
            options={'verbose_name': 'Цель на год', 'verbose_name_plural': 'Цели на год'},
        ),
        migrations.AlterModelOptions(
            name='progres',
            options={'verbose_name': 'Чтение', 'verbose_name_plural': 'Чтения'},
        ),
        migrations.AlterField(
            model_name='author',
            name='name',
            field=models.CharField(max_length=155, unique=True, verbose_name='Имя автора'),
        ),
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='booktracker.author', verbose_name='Автор книги'),
        ),
        migrations.AlterField(
            model_name='book',
            name='page_num',
            field=models.IntegerField(verbose_name='Количество страниц'),
        ),
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(max_length=155, verbose_name='Название книги'),
        ),
        migrations.AlterField(
            model_name='book',
            name='translator',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Переводчики'),
        ),
        migrations.AlterField(
            model_name='bookreview',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booktracker.book', verbose_name='Книга'),
        ),
        migrations.AlterField(
            model_name='bookreview',
            name='rating',
            field=models.IntegerField(verbose_name='Оценка'),
        ),
        migrations.AlterField(
            model_name='bookreview',
            name='text',
            field=models.TextField(verbose_name='Мюсли'),
        ),
        migrations.AlterField(
            model_name='bookreview',
            name='title',
            field=models.CharField(max_length=155, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='bookreview',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='bookusers',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='booktracker.book', verbose_name='Книга'),
        ),
        migrations.AlterField(
            model_name='bookusers',
            name='complete',
            field=models.BooleanField(default=False, verbose_name='Читаю/прочитана'),
        ),
        migrations.AlterField(
            model_name='bookusers',
            name='completed_date',
            field=models.DateField(blank=True, null=True, verbose_name='Прочитано кнги'),
        ),
        migrations.AlterField(
            model_name='bookusers',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='mood',
            name='name',
            field=models.CharField(max_length=20, verbose_name='Название эмоции'),
        ),
        migrations.AlterField(
            model_name='objectivereadingbook',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booktracker.book', verbose_name='Книга'),
        ),
        migrations.AlterField(
            model_name='objectivereadingbook',
            name='goal_read_book',
            field=models.DateField(verbose_name='Закончить к '),
        ),
        migrations.AlterField(
            model_name='objectivereadingbook',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='progres',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booktracker.book', verbose_name='Книга'),
        ),
        migrations.AlterField(
            model_name='progres',
            name='end_page',
            field=models.IntegerField(verbose_name='Страница окончания'),
        ),
        migrations.AlterField(
            model_name='progres',
            name='end_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Окончание чтения'),
        ),
        migrations.AlterField(
            model_name='progres',
            name='mood',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='booktracker.mood', verbose_name='Настроение'),
        ),
        migrations.AlterField(
            model_name='progres',
            name='start_page',
            field=models.IntegerField(verbose_name='Начальная страница'),
        ),
        migrations.AlterField(
            model_name='progres',
            name='start_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Начало чтения'),
        ),
        migrations.AlterField(
            model_name='progres',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
