# Generated by Django 4.1.5 on 2023-01-10 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booktracker', '0003_alter_author_options_alter_book_options_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='book',
            unique_together={('title', 'page_num', 'translator')},
        ),
    ]
