# Generated by Django 4.1.5 on 2023-01-10 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booktracker', '0004_alter_book_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='book',
            unique_together={('title', 'page_num', 'author')},
        ),
    ]
