# Generated by Django 4.1.5 on 2023-01-19 14:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('booktracker', '0005_alter_book_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='booktracker.author', verbose_name='Автор книги'),
        ),
        migrations.AlterUniqueTogether(
            name='bookusers',
            unique_together={('user', 'book')},
        ),
    ]
