# Generated by Django 4.1.5 on 2023-01-31 15:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booktracker', '0007_bookstatus_remove_bookusers_complete_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookusers',
            name='planed_complete',
            field=models.DateField(blank=True, null=True, verbose_name='Нужно дочитать'),
        ),
        migrations.AddField(
            model_name='bookusers',
            name='review',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bookusers',
            name='completed_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дочитана'),
        ),
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('bookusers', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booktracker.bookusers')),
            ],
        ),
    ]
