# Generated by Django 4.1.5 on 2023-02-14 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booktracker', '0008_bookusers_planed_complete_bookusers_review_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attachment',
            options={'verbose_name': 'Цитаты из книги'},
        ),
        migrations.AlterModelOptions(
            name='bookstatus',
            options={'verbose_name': 'Статус книги', 'verbose_name_plural': 'Статусы книг'},
        ),
        migrations.AlterField(
            model_name='bookreview',
            name='text',
            field=models.TextField(verbose_name='Мои мысли о книге'),
        ),
    ]
