# Generated by Django 4.1.5 on 2023-02-15 12:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('booktracker', '0009_alter_attachment_options_alter_bookstatus_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachment',
            name='page_attachment',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attachment',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='attachment',
            name='bookusers',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booktracker.bookusers', verbose_name='Пользователь'),
        ),
    ]
